version: '3'
services:
    nginx:
        image: nginx:1.16-alpine
        ports:
            - "80:80"
        # 依赖关系 先跑php
        depends_on:
            - "php"
        # 数据卷
        volumes:
            - "$PWD/nginx/conf.d:/etc/nginx/conf.d"
            - "$PWD/nginx/html:/var/www/html"
        networks:
            - app_net
        # 容器名称
        container_name: "compose-nginx"
    php:
        build: ./php
        # image指定build Dockerfile生成镜像的名称
        image: php:7.2-fpm
        ports:
            - "9000:9000"
        volumes:
            - "$PWD/nginx/html:/var/www/html"
        networks:
            - app_net
        container_name: "compose-php"
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            - MYSQL_ROOT_PASSWORD=secret
        volumes:
            - "$PWD/mysql/data:/var/lib/mysql"
        networks:
            app_net:
                ipv4_address: 10.10.10.1
        container_name: "compose-mysql"
    redis:
        image: redis:5.0.4-alpine
        ports:
          - "6379:6379"
        volumes:
          - $PWD/redis/data:/data
        restart: always
        entrypoint: ["redis-server"]
        networks:
            app_net:
                ipv4_address: 10.10.10.2
        container_name: "compose-redis"
    mongodb:
        image: "bitnami/mongodb:latest"
        ports:
          - "27017:27017"
        volumes:
            - $PWD/mongodb:/bitnami
        environment:
            - MONGODB_USERNAME=my_user
            - MONGODB_PASSWORD=secret
            - MONGODB_DATABASE=my_database
        networks:
            app_net:
                ipv4_address: 10.10.10.3
        container_name: "compose-mongodb"
networks:
    app_net:
        driver: bridge
        ipam:
            config:
                - subnet: 10.10.0.0/16
